[package]
name = "pixelforge"
version = "0.1.0"
edition = "2021"

[lib]
name = "pixelforge"
path = "src/lib.rs"

[dependencies]
minifb = "0.27.0"
thiserror = "2.0.6"

[[example]]
name = "creating_window"
path = "examples/creating_window.rs"
